table Dim_Date
	lineageTag: a1b2c3d4-0001-4000-8000-000000000001
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: a1b2c3d4-0001-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-0001-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: a1b2c3d4-0001-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-0001-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column YearMonthKey
		dataType: string
		lineageTag: a1b2c3d4-0001-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: YearMonthKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
					StartDate = #date(2023, 1, 1),
					EndDate = #date(2025, 12, 31),
					DayCount = Duration.Days(EndDate - StartDate) + 1,
					DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
					TableFromList = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					ChangedType = Table.TransformColumnTypes(TableFromList, {{"Date", type date}}),
					AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
					AddMonthNo = Table.AddColumn(AddYear, "MonthNo", each Date.Month([Date]), Int64.Type),
					AddMonthName = Table.AddColumn(AddMonthNo, "Month", each Text.Upper(Text.Start(Date.MonthName([Date], "en-US"), 3)), type text),
					AddYearMonthKey = Table.AddColumn(AddMonthName, "YearMonthKey", each Text.From([Year]) & "-" & Text.PadStart(Text.From([MonthNo]), 2, "0"), type text)
				in
					AddYearMonthKey

	annotation PBI_Id = a1b2c3d4-0001-4000-8000-000000000000

